### ISSUE TITLE
Custom message for format validation

### ISSUE THREAD

**Issue by marcocanderle** [krettan/refile-mongoid#3]
Hello,

I'm using a fork for this gem found here: https://github.com/jbrien/refile-mongoid for my project. 
Since that fork doesn't have option to open an issue and this question might be useful on your gem too I'm opening this issue here.

I need to know if there is any way of customizing the validation message returned when a file is attempted with an invalid format.

I have this on my model

```
attachment :file, type: :image
```

When I try to upload, say, a txt file, I get the "is invalid" message.

The question is, is there a way of customizing the validation message? I would like to have a validation message like: 

```
You are not allowed to upload "txt" files, allowed types: jpg, jpeg, gif, png
```

I tried replacing the corresponding locale entry but I don't know how to set it so that the allowed types and the uploaded file extension are included on the message.

Thanks!

**Comment by krettan** [comment]
Hi @marcocanderle and sorry for not getting back to you sooner!

I don't think this gem should handle customisation of messages like the one you are referring to. 

Take a look at the specs of the `refile`-gem: [normal_upload_spec.rb](/refile/refile/blob/master/spec/refile/features/normal_upload_spec.rb#L27) and [direct_upload_spec.rb](https://github.com/refile/refile/blob/07165d5adc03e8c83b2014bcf0d4ae1d4c56e440/spec/refile/features/direct_upload_spec.rb#L49), where the expected output is given.

Perhaps you should wrap your refile controller in a customisable layer where you can specify your own messages?

**Comment by marcocanderle** [comment]
Hi @krettan . Thanks for your answer!

I was trying to avoid having to customize this to get a different message. I was looking for some kind of option as paperclip gem has where you can at least specify the custom message you want by adding a "message" parameter as in this case:

```
validates_attachment :avatar,
:content_type => { :content_type => /image/, :message => "Avatar must be an image" },
:size => { :in => 0..2.megabytes, :message => "Avatar must be less than 2 megabytes in size" }
```

I guess I'll try some customization as you suggest.

Thanks!
Marco

**Comment by krettan** [comment]
@marcocanderle you could try to open a similar issue in the main `refile` repo! This is just the `mongoid`-extension so maybe that would be a better fit! I'm sure there are more people who would want this config-option.
